/* eslint-disable node/prefer-global/process */
import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const featuresDir = join(process.cwd(), "src/features");
const featureNames = await readdir(featuresDir);

const features = featureNames.filter((name) => {
  // 可以按需排除 _shared、utils 等目录
  return !name.startsWith("_");
});

const imports = features
  .map((name, index) => {
    return `import router${index} from "@/features/${name}/index.js";`;
  })
  .join("\n");

const chainedRoutes = features
  .map((_name, index) => {
    return `  .route("/api", router${index})`;
  })
  .join("\n");

const code = `
// ⚠️ Auto-generated by scripts/generate-routes.ts
// Do not edit manually.

import { createApp } from "@/core/app/create-app.js";
${imports}

export const app = createApp()
${chainedRoutes};

export type AppType = typeof app;
`.trimStart();

await writeFile(join(process.cwd(), "src/routes.generated.ts"), code);
console.log("Generated src/routes.generated.ts");
