// ⚠️ Auto-generated by scripts/generate-routes.ts
// Do not edit manually.

import { createApp } from "@/core/app/create-app.js";
import router0 from "@/features/health/index.js";

export const app = createApp()
  .route("/api", router0);

export type AppType = typeof app;
