/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Hono 后端模板 API - version 1.0.0
 *
 * 面向生产环境的 Hono 后端模板 API。
 *
 * OpenAPI version: 3.0.3
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'Health.getHealthz': ['GET', '/healthz'],
  'Health.getReadyz': ['GET', '/readyz'],
  'Health.getHealth': ['GET', '/api/v1/health'],
  'Me.getMe': ['GET', '/api/v1/me'],
  'Projects.listProjects': ['GET', '/api/v1/projects'],
  'Projects.getProjectById': ['GET', '/api/v1/projects/{projectId}'],
  'IAM.listPermissions': ['GET', '/api/v1/permissions'],
  'IAM.listRoles': ['GET', '/api/v1/roles'],
  'IAM.createRole': ['POST', '/api/v1/roles'],
  'IAM.updateRole': ['PATCH', '/api/v1/roles/{roleId}'],
  'IAM.deleteRole': ['DELETE', '/api/v1/roles/{roleId}'],
  'IAM.listRolePermissions': ['GET', '/api/v1/roles/{roleId}/permissions'],
  'IAM.assignRolePermissions': ['POST', '/api/v1/roles/{roleId}/permissions'],
  'IAM.deleteRolePermission': ['DELETE', '/api/v1/roles/{roleId}/permissions/{permission}'],
  'IAM.assignUserRole': ['POST', '/api/v1/users/{userId}/roles/{roleId}'],
  'IAM.deleteUserRole': ['DELETE', '/api/v1/users/{userId}/roles/{roleId}'],
  'IAM.assignUserPermission': ['POST', '/api/v1/users/{userId}/permissions/{permission}'],
  'IAM.deleteUserPermission': ['DELETE', '/api/v1/users/{userId}/permissions/{permission}'],
  'IAM.listUserPermissions': ['GET', '/api/v1/users/{userId}/permissions'],
  'IAM.listOrganizations': ['GET', '/api/v1/organizations'],
  'IAM.createOrganization': ['POST', '/api/v1/organizations'],
  'IAM.getOrganization': ['GET', '/api/v1/organizations/{orgId}'],
  'IAM.updateOrganization': ['PATCH', '/api/v1/organizations/{orgId}'],
  'IAM.deleteOrganization': ['DELETE', '/api/v1/organizations/{orgId}']
};
