/* tslint:disable */
/* eslint-disable */
/**
 * Hono 后端模板 API - version 1.0.0
 *
 * 面向生产环境的 Hono 后端模板 API。
 *
 * OpenAPI version: 3.0.3
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface CreateUser {
  /**
   * 邮箱(唯一)
   */
  email: string;
  /**
   * 初始密码(至少 8 位)
   */
  password: string;
  /**
   * 显示名
   */
  name: string;
}
export interface CreateOrganization {
  /**
   * 组织名
   */
  name: string;
  /**
   * 父组织 ID,不填为根组织
   */
  parentId?: string;
}
export interface HealthzStatus {
  /**
   * 进程存活
   */
  status: 'ok';
}
export interface ReadyzStatus {
  /**
   * 依赖就绪
   */
  status: 'ready';
}
export interface HealthStatus {
  /**
   * 当前服务健康状态。
   */
  status: 'ok';
}
export interface User {
  /**
   * 用户 ID
   */
  id: string;
  /**
   * 用户名
   */
  name: string;
  /**
   * 邮箱
   */
  email: string;
  /**
   * 归属组织 ID,未绑定则为 null
   */
  orgId: string | null;
}
export interface Me {
  user: User;
  /**
   * 当前组织下的有效权限名列表(空数组表示未绑定组织或无权限)
   */
  permissions: (
    | 'projects.read'
    | 'projects.create'
    | 'projects.update'
    | 'projects.delete'
    | 'iam.read'
    | 'iam.manage'
    | 'users.read'
    | 'users.create'
    | 'users.update'
    | 'users.reset-password'
    | 'users.disable'
    | 'users.enable'
    | 'settings.read'
    | 'settings.update'
  )[];
}
export interface Project {
  /**
   * 项目 ID
   */
  id: string;
  /**
   * 项目名称
   */
  name: string;
  /**
   * 项目描述,可为空
   */
  description: string | null;
  /**
   * 所属组织 ID
   */
  orgId: string;
  /**
   * 创建时间(ISO 8601)
   */
  createdAt: string;
  /**
   * 更新时间(ISO 8601)
   */
  updatedAt: string;
}
export interface Permission {
  /**
   * 权限名 <resource>.<action>
   */
  name: string;
  /**
   * 权限描述
   */
  description: string | null;
  /**
   * 创建时间(ISO 8601)
   */
  createdAt: string;
  /**
   * 更新时间(ISO 8601)
   */
  updatedAt: string;
}
export interface UserSummary {
  /**
   * 用户 ID
   */
  id: string;
  /**
   * 用户名
   */
  name: string;
  /**
   * 邮箱
   */
  email: string;
  /**
   * 归属组织 ID
   */
  orgId: string | null;
  /**
   * 是否禁用(null/false=启用)
   */
  disabled: boolean | null;
  /**
   * 创建时间(ISO 8601)
   */
  createdAt: string;
}
export interface Role {
  /**
   * 角色 ID
   */
  id: string;
  /**
   * 角色名
   */
  name: string;
  /**
   * 角色描述
   */
  description: string | null;
  /**
   * code=代码同步(不可改删),instance=管理 API 创建
   */
  source: 'code' | 'instance';
  /**
   * 创建时间(ISO 8601)
   */
  createdAt: string;
  /**
   * 更新时间(ISO 8601)
   */
  updatedAt: string;
}
export interface Organization {
  /**
   * 组织 ID
   */
  id: string;
  /**
   * 组织名
   */
  name: string;
  /**
   * 父组织 ID,根组织为 null
   */
  parentId: string | null;
  /**
   * 创建时间(ISO 8601)
   */
  createdAt: string;
  /**
   * 更新时间(ISO 8601)
   */
  updatedAt: string;
}
export interface SignUpValue {
  /**
   * 是否开启
   */
  enabled: boolean;
}
export interface SystemSetting {
  /**
   * 配置名
   */
  key: string;
  /**
   * 配置值(JSON)
   */
  value: SignUpValue;
  /**
   * 最后修改时间(ISO 8601)
   */
  updatedAt: string;
  /**
   * 最后修改者用户 ID
   */
  updatedByUserId: string | null;
}
export interface UpdateProject {
  name?: string;
  description?: string | null;
}
export interface UpdateUser {
  /**
   * 显示名
   */
  name?: string;
  /**
   * 邮箱(唯一)
   */
  email?: string;
}
export interface ResetPassword {
  /**
   * 新密码(至少 8 位)
   */
  newPassword: string;
}
export interface UpdateRole {
  name?: string;
  description?: string | null;
}
export interface UpdateOrganization {
  name?: string;
  /**
   * 新父组织 ID,null 表示改为根组织
   */
  parentId?: string | null;
}
export interface UpdateSetting {
  /**
   * 配置值(JSON)
   */
  value: SignUpValue;
}
export interface UserRoleAssignment {
  /**
   * 角色 ID
   */
  roleId: string;
  /**
   * 角色名
   */
  roleName: string;
  /**
   * 授权绑定的组织 ID
   */
  orgId: string;
  /**
   * 过期时间(ISO 8601),null 表示永不过期
   */
  expiresAt: string | null;
}
export interface UserDirectPermission {
  /**
   * 权限名 <resource>.<action>
   */
  permission: string;
  /**
   * 允许或拒绝
   */
  effect: 'allow' | 'deny';
  /**
   * 授权绑定的组织 ID
   */
  orgId: string;
  /**
   * 过期时间(ISO 8601),null 表示永不过期
   */
  expiresAt: string | null;
}
declare global {
  interface Apis {
    Health: {
      /**
       * ---
       *
       * [GET] 存活探针(liveness)
       *
       * **path:** /healthz
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 进程存活
       *   status: 'ok'
       * }
       * ```
       */
      getHealthz<Config extends Alova2MethodConfig<HealthzStatus>>(
        config?: Config
      ): Alova2Method<HealthzStatus, 'Health.getHealthz', Config>;
      /**
       * ---
       *
       * [GET] 就绪探针(readiness)
       *
       * **path:** /readyz
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 依赖就绪
       *   status: 'ready'
       * }
       * ```
       */
      getReadyz<Config extends Alova2MethodConfig<ReadyzStatus>>(
        config?: Config
      ): Alova2Method<ReadyzStatus, 'Health.getReadyz', Config>;
      /**
       * ---
       *
       * [GET] 获取服务健康状态
       *
       * **path:** /api/v1/health
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 当前服务健康状态。
       *   status: 'ok'
       * }
       * ```
       */
      getHealth<Config extends Alova2MethodConfig<HealthStatus>>(
        config?: Config
      ): Alova2Method<HealthStatus, 'Health.getHealth', Config>;
    };
    Me: {
      /**
       * ---
       *
       * [GET] 获取当前用户信息与有效权限
       *
       * **path:** /api/v1/me
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   user: {
       *     // 用户 ID
       *     id: string
       *     // 用户名
       *     name: string
       *     // 邮箱
       *     email: string
       *     // 归属组织 ID,未绑定则为 null
       *     orgId: string | null
       *   }
       *   // 当前组织下的有效权限名列表(空数组表示未绑定组织或无权限)
       *   // [items] start
       *   // [items] end
       *   permissions: (
       *     | 'projects.read'
       *     | 'projects.create'
       *     | 'projects.update'
       *     | 'projects.delete'
       *     | 'iam.read'
       *     | 'iam.manage'
       *     | 'users.read'
       *     | 'users.create'
       *     | 'users.update'
       *     | 'users.reset-password'
       *     | 'users.disable'
       *     | 'users.enable'
       *     | 'settings.read'
       *     | 'settings.update'
       *   )[]
       * }
       * ```
       */
      getMe<Config extends Alova2MethodConfig<Me>>(config?: Config): Alova2Method<Me, 'Me.getMe', Config>;
    };
    Projects: {
      /**
       * ---
       *
       * [GET] 列出当前用户组织下的项目
       *
       * **path:** /api/v1/projects
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 项目 ID
       *   id: string
       *   // 项目名称
       *   name: string
       *   // 项目描述,可为空
       *   description: string | null
       *   // 所属组织 ID
       *   orgId: string
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }>
       * ```
       */
      listProjects<Config extends Alova2MethodConfig<Project[]>>(
        config?: Config
      ): Alova2Method<Project[], 'Projects.listProjects', Config>;
      /**
       * ---
       *
       * [POST] 创建项目
       *
       * **path:** /api/v1/projects
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 项目名(同组织内唯一)
       *   name: string
       *   // 项目描述,可不填
       *   description?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 项目 ID
       *   id: string
       *   // 项目名称
       *   name: string
       *   // 项目描述,可为空
       *   description: string | null
       *   // 所属组织 ID
       *   orgId: string
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      createProject<
        Config extends Alova2MethodConfig<Project> & {
          data: {
            /**
             * 项目名(同组织内唯一)
             */
            name: string;
            /**
             * 项目描述,可不填
             */
            description?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Project, 'Projects.createProject', Config>;
      /**
       * ---
       *
       * [GET] 获取项目详情
       *
       * **path:** /api/v1/projects/{projectId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 项目 ID
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 项目 ID
       *   id: string
       *   // 项目名称
       *   name: string
       *   // 项目描述,可为空
       *   description: string | null
       *   // 所属组织 ID
       *   orgId: string
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      getProjectById<
        Config extends Alova2MethodConfig<Project> & {
          pathParams: {
            /**
             * 项目 ID
             */
            projectId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Project, 'Projects.getProjectById', Config>;
      /**
       * ---
       *
       * [PATCH] 修改项目
       *
       * **path:** /api/v1/projects/{projectId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 项目 ID
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name?: string
       *   description?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 项目 ID
       *   id: string
       *   // 项目名称
       *   name: string
       *   // 项目描述,可为空
       *   description: string | null
       *   // 所属组织 ID
       *   orgId: string
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      updateProject<
        Config extends Alova2MethodConfig<Project> & {
          pathParams: {
            /**
             * 项目 ID
             */
            projectId: string;
          };
          data: UpdateProject;
        }
      >(
        config: Config
      ): Alova2Method<Project, 'Projects.updateProject', Config>;
      /**
       * ---
       *
       * [DELETE] 删除项目
       *
       * **path:** /api/v1/projects/{projectId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 项目 ID
       *   projectId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id: string
       * }
       * ```
       */
      deleteProject<
        Config extends Alova2MethodConfig<{
          id: string;
        }> & {
          pathParams: {
            /**
             * 项目 ID
             */
            projectId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          id: string;
        },
        'Projects.deleteProject',
        Config
      >;
    };
    IAM: {
      /**
       * ---
       *
       * [GET] 列出所有权限(代码同步目录)
       *
       * **path:** /api/v1/permissions
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 权限名 <resource>.<action>
       *   name: string
       *   // 权限描述
       *   description: string | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }>
       * ```
       */
      listPermissions<Config extends Alova2MethodConfig<Permission[]>>(
        config?: Config
      ): Alova2Method<Permission[], 'IAM.listPermissions', Config>;
      /**
       * ---
       *
       * [GET] 列出当前用户组织下的用户
       *
       * **path:** /api/v1/users
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 用户 ID
       *   id: string
       *   // 用户名
       *   name: string
       *   // 邮箱
       *   email: string
       *   // 归属组织 ID
       *   orgId: string | null
       *   // 是否禁用(null/false=启用)
       *   disabled: boolean | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       * }>
       * ```
       */
      listUsers<Config extends Alova2MethodConfig<UserSummary[]>>(
        config?: Config
      ): Alova2Method<UserSummary[], 'IAM.listUsers', Config>;
      /**
       * ---
       *
       * [POST] 管理员代创建用户
       *
       * **path:** /api/v1/users
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 邮箱(唯一)
       *   email: string
       *   // 初始密码(至少 8 位)
       *   password: string
       *   // 显示名
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 用户 ID
       *   id: string
       *   // 用户名
       *   name: string
       *   // 邮箱
       *   email: string
       *   // 归属组织 ID
       *   orgId: string | null
       *   // 是否禁用(null/false=启用)
       *   disabled: boolean | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       * }
       * ```
       */
      createUser<
        Config extends Alova2MethodConfig<UserSummary> & {
          data: CreateUser;
        }
      >(
        config: Config
      ): Alova2Method<UserSummary, 'IAM.createUser', Config>;
      /**
       * ---
       *
       * [PATCH] 修改用户资料
       *
       * **path:** /api/v1/users/{userId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   userId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 显示名
       *   name?: string
       *   // 邮箱(唯一)
       *   email?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 用户 ID
       *   id: string
       *   // 用户名
       *   name: string
       *   // 邮箱
       *   email: string
       *   // 归属组织 ID
       *   orgId: string | null
       *   // 是否禁用(null/false=启用)
       *   disabled: boolean | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       * }
       * ```
       */
      updateUser<
        Config extends Alova2MethodConfig<UserSummary> & {
          pathParams: {
            /**
             * 用户 ID
             */
            userId: string;
          };
          data: UpdateUser;
        }
      >(
        config: Config
      ): Alova2Method<UserSummary, 'IAM.updateUser', Config>;
      /**
       * ---
       *
       * [POST] 重置用户密码
       *
       * **path:** /api/v1/users/{userId}/reset-password
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   userId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 新密码(至少 8 位)
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   userId: string
       * }
       * ```
       */
      resetUserPassword<
        Config extends Alova2MethodConfig<{
          userId: string;
        }> & {
          pathParams: {
            /**
             * 用户 ID
             */
            userId: string;
          };
          data: ResetPassword;
        }
      >(
        config: Config
      ): Alova2Method<
        {
          userId: string;
        },
        'IAM.resetUserPassword',
        Config
      >;
      /**
       * ---
       *
       * [POST] 禁用用户
       *
       * **path:** /api/v1/users/{userId}/disable
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   userId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 用户 ID
       *   id: string
       *   // 用户名
       *   name: string
       *   // 邮箱
       *   email: string
       *   // 归属组织 ID
       *   orgId: string | null
       *   // 是否禁用(null/false=启用)
       *   disabled: boolean | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       * }
       * ```
       */
      disableUser<
        Config extends Alova2MethodConfig<UserSummary> & {
          pathParams: {
            /**
             * 用户 ID
             */
            userId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserSummary, 'IAM.disableUser', Config>;
      /**
       * ---
       *
       * [POST] 启用用户
       *
       * **path:** /api/v1/users/{userId}/enable
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 用户 ID
       *   userId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 用户 ID
       *   id: string
       *   // 用户名
       *   name: string
       *   // 邮箱
       *   email: string
       *   // 归属组织 ID
       *   orgId: string | null
       *   // 是否禁用(null/false=启用)
       *   disabled: boolean | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       * }
       * ```
       */
      enableUser<
        Config extends Alova2MethodConfig<UserSummary> & {
          pathParams: {
            /**
             * 用户 ID
             */
            userId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserSummary, 'IAM.enableUser', Config>;
      /**
       * ---
       *
       * [GET] 列出所有角色
       *
       * **path:** /api/v1/roles
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 角色 ID
       *   id: string
       *   // 角色名
       *   name: string
       *   // 角色描述
       *   description: string | null
       *   // code=代码同步(不可改删),instance=管理 API 创建
       *   source: 'code' | 'instance'
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }>
       * ```
       */
      listRoles<Config extends Alova2MethodConfig<Role[]>>(
        config?: Config
      ): Alova2Method<Role[], 'IAM.listRoles', Config>;
      /**
       * ---
       *
       * [POST] 创建角色(实例角色)
       *
       * **path:** /api/v1/roles
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 角色名(唯一)
       *   name: string
       *   // 角色描述
       *   description?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 角色 ID
       *   id: string
       *   // 角色名
       *   name: string
       *   // 角色描述
       *   description: string | null
       *   // code=代码同步(不可改删),instance=管理 API 创建
       *   source: 'code' | 'instance'
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      createRole<
        Config extends Alova2MethodConfig<Role> & {
          data: {
            /**
             * 角色名(唯一)
             */
            name: string;
            /**
             * 角色描述
             */
            description?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Role, 'IAM.createRole', Config>;
      /**
       * ---
       *
       * [PATCH] 修改角色(仅实例角色)
       *
       * **path:** /api/v1/roles/{roleId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 角色 ID
       *   roleId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name?: string
       *   description?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 角色 ID
       *   id: string
       *   // 角色名
       *   name: string
       *   // 角色描述
       *   description: string | null
       *   // code=代码同步(不可改删),instance=管理 API 创建
       *   source: 'code' | 'instance'
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      updateRole<
        Config extends Alova2MethodConfig<Role> & {
          pathParams: {
            /**
             * 角色 ID
             */
            roleId: string;
          };
          data: UpdateRole;
        }
      >(
        config: Config
      ): Alova2Method<Role, 'IAM.updateRole', Config>;
      /**
       * ---
       *
       * [DELETE] 删除角色(仅实例角色,cascade 删 role_permissions 与 user_roles)
       *
       * **path:** /api/v1/roles/{roleId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 角色 ID
       *   roleId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id: string
       * }
       * ```
       */
      deleteRole<
        Config extends Alova2MethodConfig<{
          id: string;
        }> & {
          pathParams: {
            /**
             * 角色 ID
             */
            roleId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          id: string;
        },
        'IAM.deleteRole',
        Config
      >;
      /**
       * ---
       *
       * [GET] 列出角色含的权限
       *
       * **path:** /api/v1/roles/{roleId}/permissions
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 角色 ID
       *   roleId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      listRolePermissions<
        Config extends Alova2MethodConfig<string[]> & {
          pathParams: {
            /**
             * 角色 ID
             */
            roleId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string[], 'IAM.listRolePermissions', Config>;
      /**
       * ---
       *
       * [POST] 给角色批量配权限(仅实例角色)
       *
       * **path:** /api/v1/roles/{roleId}/permissions
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 角色 ID
       *   roleId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 要授予的权限名列表(已存在的跳过)
       *   // [items] start
       *   // [items] end
       *   permissions: string[]
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      assignRolePermissions<
        Config extends Alova2MethodConfig<string[]> & {
          pathParams: {
            /**
             * 角色 ID
             */
            roleId: string;
          };
          data: {
            /**
             * 要授予的权限名列表(已存在的跳过)
             */
            permissions: string[];
          };
        }
      >(
        config: Config
      ): Alova2Method<string[], 'IAM.assignRolePermissions', Config>;
      /**
       * ---
       *
       * [DELETE] 撤角色的单个权限(仅实例角色)
       *
       * **path:** /api/v1/roles/{roleId}/permissions/{permission}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   roleId: string
       *   permission: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   permission: string
       * }
       * ```
       */
      deleteRolePermission<
        Config extends Alova2MethodConfig<{
          permission: string;
        }> & {
          pathParams: {
            roleId: string;
            permission: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          permission: string;
        },
        'IAM.deleteRolePermission',
        Config
      >;
      /**
       * ---
       *
       * [POST] 授用户角色(绑定组织,可指定过期)
       *
       * **path:** /api/v1/users/{userId}/roles/{roleId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: string
       *   roleId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 授权绑定的组织 ID
       *   orgId: string
       *   // 过期时间(ISO 8601),不填则永不过期
       *   expiresAt?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   userId: string
       *   roleId: string
       *   orgId: string
       * }
       * ```
       */
      assignUserRole<
        Config extends Alova2MethodConfig<{
          userId: string;
          roleId: string;
          orgId: string;
        }> & {
          pathParams: {
            userId: string;
            roleId: string;
          };
          data: {
            /**
             * 授权绑定的组织 ID
             */
            orgId: string;
            /**
             * 过期时间(ISO 8601),不填则永不过期
             */
            expiresAt?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          userId: string;
          roleId: string;
          orgId: string;
        },
        'IAM.assignUserRole',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 撤用户角色(需 orgId 查询参数定位)
       *
       * **path:** /api/v1/users/{userId}/roles/{roleId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: string
       *   roleId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 目标组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   userId: string
       *   roleId: string
       *   orgId: string
       * }
       * ```
       */
      deleteUserRole<
        Config extends Alova2MethodConfig<{
          userId: string;
          roleId: string;
          orgId: string;
        }> & {
          pathParams: {
            userId: string;
            roleId: string;
          };
          params: {
            /**
             * 目标组织 ID
             */
            orgId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          userId: string;
          roleId: string;
          orgId: string;
        },
        'IAM.deleteUserRole',
        Config
      >;
      /**
       * ---
       *
       * [POST] 直接授用户权限(allow/deny,绑定组织)
       *
       * **path:** /api/v1/users/{userId}/permissions/{permission}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: string
       *   permission: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 授权绑定的组织 ID
       *   orgId: string
       *   // 允许或拒绝
       *   effect: 'allow' | 'deny'
       *   // 过期时间(ISO 8601),不填则永不过期
       *   expiresAt?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   userId: string
       *   permission: string
       *   orgId: string
       *   effect: 'allow' | 'deny'
       * }
       * ```
       */
      assignUserPermission<
        Config extends Alova2MethodConfig<{
          userId: string;
          permission: string;
          orgId: string;
          effect: 'allow' | 'deny';
        }> & {
          pathParams: {
            userId: string;
            permission: string;
          };
          data: {
            /**
             * 授权绑定的组织 ID
             */
            orgId: string;
            /**
             * 允许或拒绝
             */
            effect: 'allow' | 'deny';
            /**
             * 过期时间(ISO 8601),不填则永不过期
             */
            expiresAt?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          userId: string;
          permission: string;
          orgId: string;
          effect: 'allow' | 'deny';
        },
        'IAM.assignUserPermission',
        Config
      >;
      /**
       * ---
       *
       * [DELETE] 撤用户直接权限(需 orgId 查询参数定位)
       *
       * **path:** /api/v1/users/{userId}/permissions/{permission}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: string
       *   permission: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 目标组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   userId: string
       *   permission: string
       *   orgId: string
       * }
       * ```
       */
      deleteUserPermission<
        Config extends Alova2MethodConfig<{
          userId: string;
          permission: string;
          orgId: string;
        }> & {
          pathParams: {
            userId: string;
            permission: string;
          };
          params: {
            /**
             * 目标组织 ID
             */
            orgId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          userId: string;
          permission: string;
          orgId: string;
        },
        'IAM.deleteUserPermission',
        Config
      >;
      /**
       * ---
       *
       * [GET] 列出用户在某组织的有效权限全集
       *
       * **path:** /api/v1/users/{userId}/permissions
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 目标组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      listUserPermissions<
        Config extends Alova2MethodConfig<string[]> & {
          pathParams: {
            userId: string;
          };
          params: {
            /**
             * 目标组织 ID
             */
            orgId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<string[], 'IAM.listUserPermissions', Config>;
      /**
       * ---
       *
       * [GET] 列出用户在某组织已授的角色记录
       *
       * **path:** /api/v1/users/{userId}/roles
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 目标组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 角色 ID
       *   roleId: string
       *   // 角色名
       *   roleName: string
       *   // 授权绑定的组织 ID
       *   orgId: string
       *   // 过期时间(ISO 8601),null 表示永不过期
       *   expiresAt: string | null
       * }>
       * ```
       */
      listUserRoles<
        Config extends Alova2MethodConfig<UserRoleAssignment[]> & {
          pathParams: {
            userId: string;
          };
          params: {
            /**
             * 目标组织 ID
             */
            orgId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserRoleAssignment[], 'IAM.listUserRoles', Config>;
      /**
       * ---
       *
       * [GET] 列出用户在某组织的直接授权记录
       *
       * **path:** /api/v1/users/{userId}/direct-permissions
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   userId: string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 目标组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 权限名 <resource>.<action>
       *   permission: string
       *   // 允许或拒绝
       *   effect: 'allow' | 'deny'
       *   // 授权绑定的组织 ID
       *   orgId: string
       *   // 过期时间(ISO 8601),null 表示永不过期
       *   expiresAt: string | null
       * }>
       * ```
       */
      listUserDirectPermissions<
        Config extends Alova2MethodConfig<UserDirectPermission[]> & {
          pathParams: {
            userId: string;
          };
          params: {
            /**
             * 目标组织 ID
             */
            orgId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserDirectPermission[], 'IAM.listUserDirectPermissions', Config>;
      /**
       * ---
       *
       * [GET] 列出所有组织(扁平,前端构建树)
       *
       * **path:** /api/v1/organizations
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 组织 ID
       *   id: string
       *   // 组织名
       *   name: string
       *   // 父组织 ID,根组织为 null
       *   parentId: string | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }>
       * ```
       */
      listOrganizations<Config extends Alova2MethodConfig<Organization[]>>(
        config?: Config
      ): Alova2Method<Organization[], 'IAM.listOrganizations', Config>;
      /**
       * ---
       *
       * [POST] 创建组织(可指定父组织)
       *
       * **path:** /api/v1/organizations
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 组织名
       *   name: string
       *   // 父组织 ID,不填为根组织
       *   parentId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 组织 ID
       *   id: string
       *   // 组织名
       *   name: string
       *   // 父组织 ID,根组织为 null
       *   parentId: string | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      createOrganization<
        Config extends Alova2MethodConfig<Organization> & {
          data: CreateOrganization;
        }
      >(
        config: Config
      ): Alova2Method<Organization, 'IAM.createOrganization', Config>;
      /**
       * ---
       *
       * [GET] 获取组织详情
       *
       * **path:** /api/v1/organizations/{orgId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 组织 ID
       *   id: string
       *   // 组织名
       *   name: string
       *   // 父组织 ID,根组织为 null
       *   parentId: string | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      getOrganization<
        Config extends Alova2MethodConfig<Organization> & {
          pathParams: {
            /**
             * 组织 ID
             */
            orgId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Organization, 'IAM.getOrganization', Config>;
      /**
       * ---
       *
       * [PATCH] 修改组织(改 parentId 时防环)
       *
       * **path:** /api/v1/organizations/{orgId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name?: string
       *   // 新父组织 ID,null 表示改为根组织
       *   parentId?: string | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 组织 ID
       *   id: string
       *   // 组织名
       *   name: string
       *   // 父组织 ID,根组织为 null
       *   parentId: string | null
       *   // 创建时间(ISO 8601)
       *   createdAt: string
       *   // 更新时间(ISO 8601)
       *   updatedAt: string
       * }
       * ```
       */
      updateOrganization<
        Config extends Alova2MethodConfig<Organization> & {
          pathParams: {
            /**
             * 组织 ID
             */
            orgId: string;
          };
          data: UpdateOrganization;
        }
      >(
        config: Config
      ): Alova2Method<Organization, 'IAM.updateOrganization', Config>;
      /**
       * ---
       *
       * [DELETE] 删除组织(有子组织拒绝)
       *
       * **path:** /api/v1/organizations/{orgId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 组织 ID
       *   orgId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id: string
       * }
       * ```
       */
      deleteOrganization<
        Config extends Alova2MethodConfig<{
          id: string;
        }> & {
          pathParams: {
            /**
             * 组织 ID
             */
            orgId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          id: string;
        },
        'IAM.deleteOrganization',
        Config
      >;
    };
    Settings: {
      /**
       * ---
       *
       * [GET] 列出全部系统配置
       *
       * **path:** /api/v1/settings
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Array<{
       *   // 配置名
       *   key: string
       *   // 配置值(JSON)
       *   value: {
       *     // 是否开启
       *     enabled: boolean
       *   }
       *   // 最后修改时间(ISO 8601)
       *   updatedAt: string
       *   // 最后修改者用户 ID
       *   updatedByUserId: string | null
       * }>
       * ```
       */
      listSettings<Config extends Alova2MethodConfig<SystemSetting[]>>(
        config?: Config
      ): Alova2Method<SystemSetting[], 'Settings.listSettings', Config>;
      /**
       * ---
       *
       * [PATCH] 修改(或创建)一条系统配置
       *
       * **path:** /api/v1/settings/{key}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // 配置名
       *   key: 'signUp'
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 配置值(JSON)
       *   value: {
       *     // 是否开启
       *     enabled: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 配置名
       *   key: string
       *   // 配置值(JSON)
       *   value: {
       *     // 是否开启
       *     enabled: boolean
       *   }
       *   // 最后修改时间(ISO 8601)
       *   updatedAt: string
       *   // 最后修改者用户 ID
       *   updatedByUserId: string | null
       * }
       * ```
       */
      updateSetting<
        Config extends Alova2MethodConfig<SystemSetting> & {
          pathParams: {
            /**
             * 配置名
             */
            key: 'signUp';
          };
          data: UpdateSetting;
        }
      >(
        config: Config
      ): Alova2Method<SystemSetting, 'Settings.updateSetting', Config>;
    };
  }

  var Apis: Apis;
}
