/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedIamUsersRouteImport } from './routes/_authenticated/iam/users'
import { Route as AuthenticatedIamRolesRouteImport } from './routes/_authenticated/iam/roles'
import { Route as AuthenticatedIamOrganizationsRouteImport } from './routes/_authenticated/iam/organizations'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIamUsersRoute = AuthenticatedIamUsersRouteImport.update({
  id: '/iam/users',
  path: '/iam/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIamRolesRoute = AuthenticatedIamRolesRouteImport.update({
  id: '/iam/roles',
  path: '/iam/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIamOrganizationsRoute =
  AuthenticatedIamOrganizationsRouteImport.update({
    id: '/iam/organizations',
    path: '/iam/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/iam/organizations': typeof AuthenticatedIamOrganizationsRoute
  '/iam/roles': typeof AuthenticatedIamRolesRoute
  '/iam/users': typeof AuthenticatedIamUsersRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/iam/organizations': typeof AuthenticatedIamOrganizationsRoute
  '/iam/roles': typeof AuthenticatedIamRolesRoute
  '/iam/users': typeof AuthenticatedIamUsersRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/iam/organizations': typeof AuthenticatedIamOrganizationsRoute
  '/_authenticated/iam/roles': typeof AuthenticatedIamRolesRoute
  '/_authenticated/iam/users': typeof AuthenticatedIamUsersRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/iam/organizations'
    | '/iam/roles'
    | '/iam/users'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/iam/organizations'
    | '/iam/roles'
    | '/iam/users'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/iam/organizations'
    | '/_authenticated/iam/roles'
    | '/_authenticated/iam/users'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/iam/users': {
      id: '/_authenticated/iam/users'
      path: '/iam/users'
      fullPath: '/iam/users'
      preLoaderRoute: typeof AuthenticatedIamUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/iam/roles': {
      id: '/_authenticated/iam/roles'
      path: '/iam/roles'
      fullPath: '/iam/roles'
      preLoaderRoute: typeof AuthenticatedIamRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/iam/organizations': {
      id: '/_authenticated/iam/organizations'
      path: '/iam/organizations'
      fullPath: '/iam/organizations'
      preLoaderRoute: typeof AuthenticatedIamOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIamOrganizationsRoute: typeof AuthenticatedIamOrganizationsRoute
  AuthenticatedIamRolesRoute: typeof AuthenticatedIamRolesRoute
  AuthenticatedIamUsersRoute: typeof AuthenticatedIamUsersRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIamOrganizationsRoute: AuthenticatedIamOrganizationsRoute,
  AuthenticatedIamRolesRoute: AuthenticatedIamRolesRoute,
  AuthenticatedIamUsersRoute: AuthenticatedIamUsersRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
